/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeModelLoadResult {
  graphHandle: number
  metaJson: string
}
export declare function createContext(optionsJson: string): number
export declare function destroyContext(contextHandle: number): void
export declare function createTensor(contextHandle: number, descriptorJson: string): number
export declare function destroyTensor(contextHandle: number, tensorHandle: number): void
export declare function writeTensor(contextHandle: number, tensorHandle: number, data: Buffer): void
export declare function readTensor(contextHandle: number, tensorHandle: number): Buffer
export declare function compileGraph(contextHandle: number, graphJson: string): Promise<number>
export declare function loadWebnnModel(contextHandle: number, pathOrDir: string, optionsJson: string): Promise<NativeModelLoadResult>
export declare function dispatch(contextHandle: number, graphHandle: number, inputsJson: string, outputsJson: string): Promise<void>
export declare function destroyGraph(contextHandle: number, graphHandle: number): void
